import {
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  File,
} from "lucide-react";

const EXTENSION_MAP = {
  ".pdf": FileText,
  ".doc": FileText,
  ".docx": FileText,
  ".txt": FileText,
  ".md": FileText,
  ".png": FileImage,
  ".jpg": FileImage,
  ".jpeg": FileImage,
  ".gif": FileImage,
  ".webp": FileImage,
  ".svg": FileImage,
  ".bmp": FileImage,
  ".mp4": FileVideo,
  ".webm": FileVideo,
  ".mov": FileVideo,
  ".m4v": FileVideo,
  ".ogv": FileVideo,
  ".mp3": FileAudio,
  ".wav": FileAudio,
  ".ogg": FileAudio,
  ".zip": FileArchive,
  ".rar": FileArchive,
  ".7z": FileArchive,
  ".tar": FileArchive,
  ".gz": FileArchive,
  ".js": FileCode,
  ".jsx": FileCode,
  ".ts": FileCode,
  ".tsx": FileCode,
  ".json": FileCode,
  ".html": FileCode,
  ".css": FileCode,
  ".xls": FileSpreadsheet,
  ".xlsx": FileSpreadsheet,
  ".csv": FileSpreadsheet,
};

export const fileIconFor = (extension) => EXTENSION_MAP[extension?.toLowerCase()] ?? File;
